version: '3'

tasks:
  run:
    cmds:
      - go run main.go
  db-up:
    dir: 'db/migration'
    cmds:
      - migrate --path . --database "postgresql://postgres:mysecretpassword@localhost:5432/simple_bank?sslmode=disable" -verbose up
  db-down:
    dir: 'db/migration'
    cmds:
      - migrate --path . --database "postgresql://postgres:mysecretpassword@localhost:5432/simple_bank?sslmode=disable" -verbose down
  sqlc-generate:
    dir: 'db'
    cmds:
      - sqlc generate
  from-working-directory:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - pwd