version: '3'

tasks:
  run:
    cmds:
      - air
  db-up:
    dir: 'db/migration'
    cmds:
      - migrate --path . --database "postgresql://postgres:mysecretpassword@localhost:5432/simple_bank?sslmode=disable" -verbose up
  db-down:
    dir: 'db/migration'
    cmds:
      - migrate --path . --database "postgresql://postgres:mysecretpassword@localhost:5432/simple_bank?sslmode=disable" -verbose down
  sqlc-generate:
    dir: 'db'
    cmds:
      - sqlc generate
  generate-mocks:
    cmds:
      - mockgen -package mockdb -destination db/mock/store.go github.com/louischering/simplebank/db/sqlc Store
  from-working-directory:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - pwd